version: '3'

services:
  hosiptalapi:
    image: hosiptalapi:dev
    environment:
      - DOTNET_USE_POLLING_FILE_WATCHER=1
      #- NUGET_FALLBACK_PACKAGES=$container_paths_to_fallback_packages_hosiptalapi$
    volumes:
      - C:\Users\Khuong\Desktop\GitHub\HopsitalStatisticsDBT\HosiptalApi:/app
      - C:\Users\Khuong\vsdbg\vs2017u5:/remote_debugger:ro
#$nuget_volume_mapping_hosiptalapi$
    entrypoint: tail -f /dev/null
    labels:
      com.microsoft.visualstudio.debuggee.program: "dotnet"
      #com.microsoft.visualstudio.debuggee.arguments: " $debuggee_arguments_probing_paths_hosiptalapi$ bin/Debug/netcoreapp2.0/HospitalApi.dll"
      com.microsoft.visualstudio.debuggee.workingdirectory: "/app"
      com.microsoft.visualstudio.debuggee.killprogram: "/bin/bash -c \"if PID=$$(pidof -x dotnet); then kill $$PID; fi\""
